import { ORGANIZATION_NAME } from '../../constants/enums';
import { formatDate, formatDateTime } from '../date';
import {
  FONT_BOLD,
  FONT_REGULAR,
  PDF_THEME,
  cellValue,
  getFrame,
  resolveLocalLogoPath,
} from './pdfTheme';

export const drawHeader = (
  doc: PDFKit.PDFDocument,
  input: {
    title: string;
    subtitle?: string;
    logoPath?: string | null;
    generatedBy: string;
    generatedAt: Date;
  },
): void => {
  const frame = getFrame(doc);
  const top = doc.page.margins.top;
  const logoPath = resolveLocalLogoPath(input.logoPath);
  if (logoPath) {
    try {
      doc.image(logoPath, frame.left, top - 4, { fit: [34, 34] });
    } catch {
      /* unsupported image — fall back to the text only header */
    }
  }
  const textLeft = logoPath ? frame.left + 44 : frame.left;

  doc.font(FONT_BOLD).fontSize(12).fillColor(PDF_THEME.primary)
    .text(ORGANIZATION_NAME, textLeft, top, { width: frame.usableWidth - 40 });
  doc.font(FONT_REGULAR).fontSize(8).fillColor(PDF_THEME.muted)
    .text(
      `Generated: ${formatDateTime(input.generatedAt)}   •   Generated by: ${input.generatedBy}`,
      textLeft,
      doc.y + 2,
      { width: frame.usableWidth - 40 },
    );

  doc.font(FONT_BOLD).fontSize(16).fillColor(PDF_THEME.ink)
    .text(input.title, frame.left, top + 42, { width: frame.usableWidth });
  if (input.subtitle) {
    doc.font(FONT_REGULAR).fontSize(9).fillColor(PDF_THEME.muted)
      .text(input.subtitle, frame.left, doc.y + 2, { width: frame.usableWidth });
  }
  doc.moveTo(frame.left, doc.y + 8).lineTo(frame.left + frame.usableWidth, doc.y + 8)
    .lineWidth(1).strokeColor(PDF_THEME.primary).stroke();
  doc.y += 18;
};

export const drawFilters = (
  doc: PDFKit.PDFDocument,
  filters: Array<{ label: string; value: string }>,
): void => {
  const frame = getFrame(doc);
  const visible = filters.filter((item) => item.value && item.value.toLowerCase() !== 'all');
  if (visible.length === 0) return;

  doc.font(FONT_BOLD).fontSize(8.5).fillColor(PDF_THEME.ink).text('Filters', frame.left, doc.y);
  doc.y += 12;
  const columnWidth = frame.usableWidth / 2;
  for (let index = 0; index < visible.length; index += 2) {
    const rowItems = visible.slice(index, index + 2);
    const startY = doc.y;
    let rowHeight = 0;
    rowItems.forEach((item, columnIndex) => {
      const x = frame.left + columnIndex * columnWidth;
      doc.font(FONT_REGULAR).fontSize(8.5).fillColor(PDF_THEME.muted)
        .text(`${item.label}: `, x, startY, { continued: true, width: columnWidth - 8 });
      doc.fillColor(PDF_THEME.ink).text(item.value);
      rowHeight = Math.max(rowHeight, doc.y - startY);
    });
    doc.y = startY + rowHeight + 2;
  }
  doc.y += 6;
};

export const drawSummary = (
  doc: PDFKit.PDFDocument,
  summary: Array<{ label: string; value: string | number }>,
): void => {
  if (summary.length === 0) return;
  const frame = getFrame(doc);
  const perRow = Math.min(4, summary.length);
  const gap = 8;
  const cardWidth = (frame.usableWidth - gap * (perRow - 1)) / perRow;
  const cardHeight = 40;
  for (let index = 0; index < summary.length; index += perRow) {
    const chunk = summary.slice(index, index + perRow);
    if (doc.y + cardHeight > frame.bottomLimit) doc.addPage();
    const top = doc.y;
    chunk.forEach((item, columnIndex) => {
      const x = frame.left + columnIndex * (cardWidth + gap);
      doc.roundedRect(x, top, cardWidth, cardHeight, 4)
        .lineWidth(1).strokeColor(PDF_THEME.border).stroke();
      doc.font(FONT_REGULAR).fontSize(7).fillColor(PDF_THEME.muted)
        .text(item.label.toUpperCase(), x + 8, top + 8, { width: cardWidth - 16 });
      doc.font(FONT_BOLD).fontSize(13).fillColor(PDF_THEME.ink)
        .text(cellValue(item.value), x + 8, top + 19, { width: cardWidth - 16 });
    });
    doc.y = top + cardHeight + gap;
  }
};

export const drawFooter = (
  doc: PDFKit.PDFDocument,
  title: string,
  generatedAt: Date,
): void => {
  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(range.start + index);
    const frame = getFrame(doc);
    const footerY = doc.page.height - doc.page.margins.bottom + 24;
    doc.moveTo(frame.left, footerY - 10).lineTo(frame.left + frame.usableWidth, footerY - 10)
      .lineWidth(0.5).strokeColor(PDF_THEME.border).stroke();
    doc.font(FONT_REGULAR).fontSize(7.5).fillColor(PDF_THEME.muted)
      .text(`${ORGANIZATION_NAME} • ${title}`, frame.left, footerY, {
        width: frame.usableWidth - 130,
      });
    doc.font(FONT_REGULAR).fontSize(7.5).fillColor(PDF_THEME.muted)
      .text(`Page ${index + 1} of ${range.count}`, frame.left, footerY, {
        width: frame.usableWidth,
        align: 'right',
      });
    doc.font(FONT_REGULAR).fontSize(7.5).fillColor(PDF_THEME.muted)
      .text(`Generated ${formatDate(generatedAt)}`, frame.left, footerY + 11, {
        width: frame.usableWidth,
      });
  }
};
