export const ENUM_LABELS: Record<string, string> = {
  PENDING: 'Pending',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  SUSPENDED: 'Suspended',
  ARCHIVED: 'Archived',
  DRAFT: 'Draft',
  PENDING_REVIEW: 'Pending Review',
  APPROVED: 'Approved',
  SCHEDULED: 'Scheduled',
  PUBLISHED: 'Published',
  REJECTED: 'Rejected',
  ONGOING: 'Ongoing',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  MEETING: 'Meeting',
  TRAINING: 'Training',
  AWARENESS_PROGRAM: 'Awareness Program',
  COMMUNITY_PROGRAM: 'Community Program',
  SPORTS: 'Sports',
  CULTURAL: 'Cultural',
  SOCIAL_SERVICE: 'Social Service',
  WORKSHOP: 'Workshop',
  OTHER: 'Other',
  NEWS: 'News',
  DISTRICT_UPDATE: 'District Update',
  UNIT_UPDATE: 'Unit Update',
  ACTIVITY: 'Activity',
  EVENT_STORY: 'Event Story',
  COMMUNITY_STORY: 'Community Story',
  AWARENESS: 'Awareness',
  MEETING_REPORT: 'Meeting Report',
  ACHIEVEMENT: 'Achievement',
  PHOTO_GALLERY: 'Photo Gallery',
  VIDEO: 'Video',
  PUBLIC: 'Public',
  MEMBERS_ONLY: 'Members Only',
  DISTRICT_ONLY: 'District Only',
  UNIT_ONLY: 'Unit Only',
  COMMUNITY_ONLY: 'Community Only',
  COMMITTEE_ONLY: 'Committee Only',
  DISTRICT: 'District',
  UNIT: 'Unit',
  COMMUNITY: 'Community',
  COMMITTEE: 'Committee',
  SELECTED_MEMBERS: 'Selected Members',
  MALE: 'Male',
  FEMALE: 'Female',
  REGULAR: 'Normal Member',
  DISTRICT_CHIEF: 'District Chief',
  JOINT_SECRETARY: 'Joint Secretary',
  JOINT_TREASURER: 'Joint Treasurer',
  COORDINATOR: 'Coordinator',
  VOLUNTEER: 'Volunteer',
  PARENTS: 'Parents',
  WOMEN: 'Women',
  YOUTH: 'Youth',
  GENERAL: 'General',
  PRESENT: 'Present',
  ABSENT: 'Absent',
  LATE: 'Late',
  EXCUSED: 'Excused',
  CHAIRPERSON: 'Chairperson',
  VICE_CHAIRPERSON: 'Vice Chairperson',
  SECRETARY: 'Secretary',
  TREASURER: 'Treasurer',
  ADVISOR: 'Advisor',
  MEMBER: 'Member',
  IMAGE: 'Images',
  UPLOAD: 'Uploaded',
  YOUTUBE: 'YouTube',
  VIMEO: 'Vimeo',
  EXTERNAL: 'External',
  PDF: 'PDF',
  EXCEL: 'Excel',
  CSV: 'CSV',
  JSON: 'JSON',
  MEETING_MINUTES: 'Meeting Minutes',
  REPORTS: 'Reports',
  NOTICES: 'Notices',
  CERTIFICATES: 'Certificates',
  GUIDELINES: 'Guidelines',
  COMMITTEE_DOCUMENTS: 'Committee Documents',
  EVENT_DOCUMENTS: 'Event Documents',
  OFFICIAL_DOCUMENTS: 'Official Documents',
  ANNOUNCEMENT: 'Announcement',
  EVENT: 'Event',
  REMINDER: 'Reminder',
  ATTENDANCE: 'Attendance',
  COMMITTEE_UPDATE: 'Committee Update',
  MEMBERSHIP_UPDATE: 'Membership Update',
  CONTENT_APPROVAL: 'Content Approval',
  CONTENT_PUBLISHED: 'Content Published',
  SYSTEM: 'System',
  LOGIN: 'Login',
  LOGIN_FAILED: 'Login Failed',
  LOGOUT: 'Logout',
  CREATE: 'Create',
  UPDATE: 'Update',
  DELETE: 'Delete',
  PUBLISH: 'Publish',
  UNPUBLISH: 'Unpublish',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  SUBMIT: 'Submit',
  SCHEDULE: 'Schedule',
  EXPORT: 'Export',
  ROLE_CHANGE: 'Role Change',
  PERMISSION_CHANGE: 'Permission Change',
  MEMBER_CREATION: 'Member Creation',
  ADMIN_CREATION: 'Admin Creation',
  ACTIVATION: 'Activation',
  DEACTIVATION: 'Deactivation',
  PASSWORD_RESET: 'Password Reset',
  PASSWORD_CHANGE: 'Password Change',
  SCOPE_CHANGE: 'Scope Change',
};

/** Known enum value -> readable label; falls back to a humanized version. */
export const label = (value?: string | null): string => {
  if (!value) return '-';
  return ENUM_LABELS[value] ?? value;
};

/** `AWARENESS_PROGRAM` -> `Awareness Program` (used for unknown enum values). */
export const humanize = (value?: string | null): string => {
  if (!value) return '-';
  const known = ENUM_LABELS[value];
  if (known) return known;
  return value
    .toLowerCase()
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
};
