import { Router } from 'express';
import { authRoutes } from '../modules/auth/auth.routes';
import { districtRoutes } from '../modules/district/district.routes';
import { unitRoutes } from '../modules/units/unit.routes';
import { communityRoutes } from '../modules/communities/community.routes';
import { committeeRoutes } from '../modules/committees/committee.routes';
import { memberRoutes } from '../modules/members/member.routes';
import { eventRoutes } from '../modules/events/event.routes';
import { attendanceRoutes } from '../modules/attendance/attendance.routes';
import { contentRoutes } from '../modules/content/content.routes';
import { announcementRoutes } from '../modules/announcements/announcement.routes';
import { mediaRoutes } from '../modules/media/media.routes';
import { documentRoutes } from '../modules/documents/document.routes';
import { notificationRoutes } from '../modules/notifications/notification.routes';
import { reportRoutes } from '../modules/reports/report.routes';
import { organizationRoutes } from '../modules/organization/organization.routes';
import { auditLogRoutes } from '../modules/auditLogs/auditLog.routes';
import { administratorRoutes } from '../modules/administrators/administrator.routes';
import { roleRoutes } from '../modules/roles/role.routes';
import { permissionRoutes } from '../modules/permissions/permission.routes';
import { userRoutes } from '../modules/users/user.routes';
import { settingsRoutes } from '../modules/settings/settings.routes';
import { searchRoutes } from '../modules/search/search.routes';
import { contactMessageRoutes } from '../modules/contactMessages/contactMessage.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/organization', organizationRoutes);
apiRouter.use('/districts', districtRoutes);
apiRouter.use('/units', unitRoutes);
apiRouter.use('/communities', communityRoutes);
apiRouter.use('/committees', committeeRoutes);
apiRouter.use('/members', memberRoutes);
apiRouter.use('/events', eventRoutes);
apiRouter.use('/attendance', attendanceRoutes);
apiRouter.use('/content', contentRoutes);
apiRouter.use('/announcements', announcementRoutes);
apiRouter.use('/media', mediaRoutes);
apiRouter.use('/documents', documentRoutes);
apiRouter.use('/notifications', notificationRoutes);
apiRouter.use('/reports', reportRoutes);
apiRouter.use('/audit-logs', auditLogRoutes);
apiRouter.use('/administrators', administratorRoutes);
apiRouter.use('/roles', roleRoutes);
apiRouter.use('/permissions', permissionRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/search', searchRoutes);
apiRouter.use('/contact-messages', contactMessageRoutes);
