export const CONTENT_TYPE = {
  NEWS: 'NEWS',
  DISTRICT_UPDATE: 'DISTRICT_UPDATE',
  UNIT_UPDATE: 'UNIT_UPDATE',
  ACTIVITY: 'ACTIVITY',
  EVENT_STORY: 'EVENT_STORY',
  COMMUNITY_STORY: 'COMMUNITY_STORY',
  AWARENESS: 'AWARENESS',
  TRAINING: 'TRAINING',
  MEETING_REPORT: 'MEETING_REPORT',
  ACHIEVEMENT: 'ACHIEVEMENT',
  PHOTO_GALLERY: 'PHOTO_GALLERY',
  VIDEO: 'VIDEO',
  OTHER: 'OTHER',
} as const;
export type ContentType = (typeof CONTENT_TYPE)[keyof typeof CONTENT_TYPE];

export const CONTENT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  SCHEDULED: 'SCHEDULED',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED',
} as const;
export type ContentStatus = (typeof CONTENT_STATUS)[keyof typeof CONTENT_STATUS];

/** Statuses reachable through public (unauthenticated) endpoints. */
export const PUBLIC_CONTENT_STATUSES: ContentStatus[] = [
  CONTENT_STATUS.PUBLISHED,
  CONTENT_STATUS.SCHEDULED,
];

export const VISIBILITY = {
  PUBLIC: 'PUBLIC',
  MEMBERS_ONLY: 'MEMBERS_ONLY',
  DISTRICT_ONLY: 'DISTRICT_ONLY',
  UNIT_ONLY: 'UNIT_ONLY',
  COMMUNITY_ONLY: 'COMMUNITY_ONLY',
  COMMITTEE_ONLY: 'COMMITTEE_ONLY',
} as const;
export type Visibility = (typeof VISIBILITY)[keyof typeof VISIBILITY];

export const TARGET_TYPE = {
  DISTRICT: 'DISTRICT',
  UNIT: 'UNIT',
  COMMUNITY: 'COMMUNITY',
  COMMITTEE: 'COMMITTEE',
  SELECTED_MEMBERS: 'SELECTED_MEMBERS',
} as const;
export type TargetType = (typeof TARGET_TYPE)[keyof typeof TARGET_TYPE];

export const DOCUMENT_CATEGORY = {
  MEETING_MINUTES: 'MEETING_MINUTES',
  REPORTS: 'REPORTS',
  NOTICES: 'NOTICES',
  CERTIFICATES: 'CERTIFICATES',
  GUIDELINES: 'GUIDELINES',
  COMMITTEE_DOCUMENTS: 'COMMITTEE_DOCUMENTS',
  EVENT_DOCUMENTS: 'EVENT_DOCUMENTS',
  OFFICIAL_DOCUMENTS: 'OFFICIAL_DOCUMENTS',
} as const;
export type DocumentCategory =
  (typeof DOCUMENT_CATEGORY)[keyof typeof DOCUMENT_CATEGORY];

export const MEDIA_CATEGORY = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;
export type MediaCategory = (typeof MEDIA_CATEGORY)[keyof typeof MEDIA_CATEGORY];

export const VIDEO_TYPE = {
  UPLOAD: 'UPLOAD',
  YOUTUBE: 'YOUTUBE',
  VIMEO: 'VIMEO',
  EXTERNAL: 'EXTERNAL',
} as const;
export type VideoType = (typeof VIDEO_TYPE)[keyof typeof VIDEO_TYPE];

/** Hosts accepted for external video embeds. */
export const VIDEO_PROVIDER_HOSTS = [
  'youtube.com',
  'www.youtube.com',
  'm.youtube.com',
  'youtu.be',
  'vimeo.com',
  'www.vimeo.com',
  'player.vimeo.com',
];

export const NOTIFICATION_TYPE = {
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  EVENT: 'EVENT',
  REMINDER: 'REMINDER',
  ATTENDANCE: 'ATTENDANCE',
  COMMITTEE_UPDATE: 'COMMITTEE_UPDATE',
  MEMBERSHIP_UPDATE: 'MEMBERSHIP_UPDATE',
  CONTENT_APPROVAL: 'CONTENT_APPROVAL',
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  CONTACT_MESSAGE: 'CONTACT_MESSAGE',
  SYSTEM: 'SYSTEM',
} as const;
export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const AUDIT_ACTION = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  PUBLISH: 'PUBLISH',
  UNPUBLISH: 'UNPUBLISH',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  SUBMIT: 'SUBMIT',
  SCHEDULE: 'SCHEDULE',
  EXPORT: 'EXPORT',
  ROLE_CHANGE: 'ROLE_CHANGE',
  PERMISSION_CHANGE: 'PERMISSION_CHANGE',
  MEMBER_CREATION: 'MEMBER_CREATION',
  ADMIN_CREATION: 'ADMIN_CREATION',
  ACTIVATION: 'ACTIVATION',
  DEACTIVATION: 'DEACTIVATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  SCOPE_CHANGE: 'SCOPE_CHANGE',
} as const;
export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export const REPORT_TYPE = {
  MEMBER: 'MEMBER',
  UNIT: 'UNIT',
  COMMUNITY: 'COMMUNITY',
  COMMITTEE: 'COMMITTEE',
  EVENT: 'EVENT',
  ATTENDANCE: 'ATTENDANCE',
  CONTENT: 'CONTENT',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ACTIVITY: 'ACTIVITY',
} as const;
export type ReportType = (typeof REPORT_TYPE)[keyof typeof REPORT_TYPE];

export const EXPORT_FORMAT = {
  PDF: 'PDF',
  EXCEL: 'EXCEL',
  CSV: 'CSV',
  JSON: 'JSON',
} as const;
export type ExportFormat = (typeof EXPORT_FORMAT)[keyof typeof EXPORT_FORMAT];

export const COMMUNITY_TARGET_GROUP = {
  PARENTS: 'PARENTS',
  WOMEN: 'WOMEN',
  YOUTH: 'YOUTH',
  GENERAL: 'GENERAL',
} as const;
export type CommunityTargetGroup =
  (typeof COMMUNITY_TARGET_GROUP)[keyof typeof COMMUNITY_TARGET_GROUP];
