import { PERMISSION_CATALOG } from './permissionCatalog';
import { ALL_PERMISSIONS, PERMISSIONS } from './permissions';
import type { Permission } from './permissions';
import { ROLE_NAMES } from './roles';
import type { RoleName } from './roles';

const grant = (permissions: Permission[]): Permission[] => [...permissions];
const except = (excluded: Permission[]): Permission[] =>
  ALL_PERMISSIONS.filter((permission) => !excluded.includes(permission));

const DISTRICT_ADMIN_EXCLUDED: Permission[] = [
  PERMISSIONS.ORGANIZATION_UPDATE,
  PERMISSIONS.ADMIN_ACCOUNT_CREATE,
  PERMISSIONS.ADMIN_ACCOUNT_UPDATE,
  PERMISSIONS.ADMIN_ACCOUNT_DEACTIVATE,
  PERMISSIONS.ADMIN_ACCOUNT_SUSPEND,
  PERMISSIONS.ADMIN_ACCOUNT_ASSIGN_SCOPE,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.ROLE_MANAGE,
  PERMISSIONS.PERMISSION_MANAGE,
  PERMISSIONS.SETTINGS_MANAGE,
];

const UNIT_ADMIN_EXCLUDED: Permission[] = [
  ...DISTRICT_ADMIN_EXCLUDED,
  PERMISSIONS.UNIT_CREATE,
  PERMISSIONS.UNIT_DELETE,
  PERMISSIONS.COMMUNITY_DELETE,
  PERMISSIONS.DISTRICT_UPDATE,
  PERMISSIONS.CONTENT_APPROVE,
  PERMISSIONS.AUDIT_VIEW,
];

/**
 * Default permission matrix. Seeded into the Role collection and maintainable
 * later through `role.manage` / `permission.manage`.
 */
export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  SUPER_ADMIN: grant(ALL_PERMISSIONS),

  DISTRICT_ADMIN: except(DISTRICT_ADMIN_EXCLUDED),

  DISTRICT_COMMITTEE_MEMBER: grant([
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.DISTRICT_VIEW,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMITTEE_VIEW,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.PORTAL_ACCESS,
    PERMISSIONS.PROFILE_SELF_UPDATE,
  ]),

  UNIT_ADMIN: except(UNIT_ADMIN_EXCLUDED),

  UNIT_COMMITTEE_MEMBER: grant([
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.DISTRICT_VIEW,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMITTEE_VIEW,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.PORTAL_ACCESS,
    PERMISSIONS.PROFILE_SELF_UPDATE,
  ]),

  COMMUNITY_COORDINATOR: grant([
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.DISTRICT_VIEW,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.COMMITTEE_VIEW,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.PORTAL_ACCESS,
    PERMISSIONS.PROFILE_SELF_UPDATE,
  ]),

  COMMITTEE_MEMBER: grant([
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.DISTRICT_VIEW,
    PERMISSIONS.UNIT_VIEW,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.COMMITTEE_VIEW,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.PORTAL_ACCESS,
    PERMISSIONS.PROFILE_SELF_UPDATE,
  ]),

  MEMBER: grant([PERMISSIONS.PORTAL_ACCESS, PERMISSIONS.PROFILE_SELF_UPDATE]),
};

/** Roles administrated through the Administrators module (never the public site). */
export const ADMIN_MANAGED_ROLES: RoleName[] = [
  ROLE_NAMES.DISTRICT_ADMIN,
  ROLE_NAMES.DISTRICT_COMMITTEE_MEMBER,
  ROLE_NAMES.UNIT_ADMIN,
  ROLE_NAMES.UNIT_COMMITTEE_MEMBER,
  ROLE_NAMES.COMMUNITY_COORDINATOR,
  ROLE_NAMES.COMMITTEE_MEMBER,
];

/** Permissions the Super Admin may never strip from any role (break-glass set). */
export const REQUIRED_PERMISSIONS: Permission[] = [PERMISSIONS.PORTAL_ACCESS];

export const permissionsForRole = (role: RoleName): Permission[] =>
  ROLE_PERMISSIONS[role] ?? [];

export const permissionModuleNames = (): string[] =>
  Array.from(new Set(PERMISSION_CATALOG.map((entry) => entry.module))).sort();
